name: mainDev
on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]
jobs:
 build-and-test:
  runs-on: ios-latest
  steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo Xcode-select -switch /Applications/Xcode_14.3.1.app
    - name: Build & Test
      run: xcodebuild clean build test -workspace project.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.1'
