name: mainDev
on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]
jobs:
 build-and-test:
  runs-on: macos-latest
  steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode_13.app # Specify the path to your Xcode version
        sudo xcodebuild -license accept
    - name: Build & Test
      run: |
        xcodebuild clean build -workspace Todoey.xcworkspace -scheme Todoey -destination "platform=iOS Simulator,name=iPhone 12" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        xcodebuild test -workspace Todoey.xcworkspace -scheme Todoey -destination "platform=iOS Simulator,name=iPhone 12"
