name: mainDev

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Install Dependencies
      #   run: |
      #     gem install bundler
      #     bundle install
      #     bundle exec pod install

      - name: Build & Test
        run: |
          xcodebuild clean build -workspace Todoey.xcworkspace -scheme Todoey -destination "platform=iOS Simulator,name=iPhone 12" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
