name: mainDev
on:
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]
jobs:
 build-and-test:
  runs-on: macos-latest
  steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      uses: actions/setup-xcode@v2
      with:
       xcode-version: "14.2"
    - name: Build & Test
      run: |
        xcodebuild clean build -workspace Todoey.xcworkspace -scheme Todoey -destination "platform=iOS Simulator,name=iPhone 12" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        xcodebuild test -workspace Todoey.xcworkspace -scheme Todoey -destination "platform=iOS Simulator,name=iPhone 12"
